<?php

namespace Hounddd\MailDkim\Console;

use Hounddd\MailDkim\Classes\DkimMailSigner;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Mail;
use Symfony\Component\Mime\Email;

/**
 * Sends a test email using current mail transport and DKIM configuration.
 *
 * @category Hounddd
 * @package  Hounddd\MailDkim
 * @author   Damien Mathieu <damien@hounddd.fr>
 * @license  MIT https://opensource.org/licenses/MIT
 * @link     https://github.com/Hounddd/wn-maildkim-plugin
 */
class SendDkimTestEmail extends Command
{
    /**
     * @var string
     */
    protected $signature = 'maildkim:send-test
        {to : Recipient email address}
        {--from= : Sender email address}
        {--subject=DKIM test email : Subject line}';

    /**
     * @var string
     */
    protected $description = 'Sends a test email and validates DKIM can sign messages.';

    /**
     * Sends a test email.
     *
     * @return int
     */
    public function handle(): int
    {
        $to = trim((string) $this->argument('to'));
        if (!filter_var($to, FILTER_VALIDATE_EMAIL)) {
            $this->error('Invalid recipient email address.');

            return 1;
        }

        $fromOption = trim((string) ($this->option('from') ?? ''));
        $defaultFrom = trim((string) config('mail.from.address', ''));
        $from = $fromOption !== '' ? $fromOption : $defaultFrom;
        if ($from === '' || !filter_var($from, FILTER_VALIDATE_EMAIL)) {
            $this->error('Missing or invalid sender address. Use --from= or configure mail.from.address.');

            return 1;
        }

        $subject = trim((string) ($this->option('subject') ?? 'DKIM test email'));
        if ($subject === '') {
            $subject = 'DKIM test email';
        }

        /* @var DkimMailSigner $signer */
        $signer = $this->laravel->make(DkimMailSigner::class);
        $issues = $signer->getConfigurationIssues();

        if (!empty($issues)) {
            $this->error('Cannot send DKIM test email due to configuration issues:');
            foreach ($issues as $issue) {
                $this->line('- ' . $issue);
            }

            return 1;
        }

        $sample = (new Email())
            ->from($from)
            ->to($to)
            ->subject($subject)
            ->text('DKIM test email preview to validate signing capability.');

        if (!$signer->signSymfonyEmail($sample)) {
            $this->error('DKIM signature could not be applied to sample message.');

            return 1;
        }

        try {
            Mail::raw(
                'This is a DKIM transport test email generated by maildkim:send-test.',
                function ($message) use ($from, $to, $subject): void {
                    $message->from($from)
                        ->to($to)
                        ->subject($subject);
                }
            );
        } catch (\Throwable $exception) {
            $this->error('Mail transport failed while sending test email.');
            $this->line($exception->getMessage());

            return 1;
        }

        $this->info('Test email sent successfully.');
        $this->line('Recipient: ' . $to);
        $this->line('Sender: ' . $from);
        $this->line('Subject: ' . $subject);
        $this->line('Tip: inspect received message headers for DKIM-Signature validation.');

        return 0;
    }
}
